// 易经六十四卦完整数据
const hexagramsData = [
    {
        "id": 1,
        "name": "乾卦",
        "pinyin": "qián Guà",
        "symbol": "䷀",
        "hexagramText": "《乾》：元亨，利贞。",
        "yaoTexts": [
            "初九：潜龙勿用。",
            "九二：见龙在田，利见大人。",
            "九三：君子终日乾乾，夕惕若厉，无咎。",
            "九四：或跃在渊，无咎。",
            "九五：飞龙在天，利见大人。",
            "上九：亢龙有悔。",
            "用九：见群龙无首，吉。"
        ],
        "fullName": "乾为天（乾卦）",
        "characteristics": "自强不息",
        "level": "上上卦",
        "xiangYue": "困龙得水好运交，不由喜气上眉梢，一切谋望皆如意，向后时运渐渐高。",
        "description": "这个卦是同卦（下乾上乾）相叠。象征天，喻龙（德才的君子），又象征纯粹的阳和健，表明兴盛强健。乾卦是根据万物变通的道理，以\"元、亨、利、贞\"为卦辞，示吉祥如意，教导人遵守天道的德行。",
        "alias": "乾为天",
        "upperTrigram": "乾",
        "lowerTrigram": "乾",
        "mutualHexagram": 1,
        "reverseHexagram": 1,
        "oppositeHexagram": 2
    },
    {
        "id": 2,
        "name": "坤卦",
        "pinyin": "Kūn Guà",
        "symbol": "䷁",
        "hexagramText": "《坤》：元亨，利牝马之贞。君子有攸往，先迷后得主，利；西南得朋，东北丧朋，安贞吉。",
        "yaoTexts": [
            "初六：履霜，坚冰至。",
            "六二：直，方，大；不习，无不利。",
            "六三：含章，可贞。或从王事，无成有终。",
            "六四：括囊，无咎无誉。",
            "六五：黄裳，元吉。",
            "上六：龙战于野，其血玄黄。",
            "用六：利永贞。"
        ],
        "fullName": "坤为地（坤卦）",
        "characteristics": "厚德载物",
        "level": "上上卦",
        "xiangYue": "肥羊失群入山岗，饿虎逢之把口张，适口充肠心欢喜，卦若占之大吉昌。",
        "description": "这个卦是同卦（下坤上坤）相叠，阴性。象征地（与乾卦相反），顺从天。承载万物，伸展无穷无尽。坤卦以雌马为象征，表明地道生育抚养万物，而又依天顺时，性情温顺。它以\"先迷后得\"证明\"坤\"顺从\"乾\"，依随\"乾\"，才能把握正确方向，遵循正道，获取吉利。",
        "alias": "坤为地",
        "upperTrigram": "坤",
        "lowerTrigram": "坤",
        "mutualHexagram": 2,
        "reverseHexagram": 2,
        "oppositeHexagram": 1
    },
    {
        "id": 3,
        "name": "屯卦",
        "pinyin": "Zhūn Guà",
        "symbol": "䷂",
        "hexagramText": "《屯》：元亨，利贞。勿用有攸往。利建侯。",
        "yaoTexts": [
            "初九：磐桓。利居贞。利建侯。",
            "六二：屯如邅如。乘马班如。匪寇。婚媾。女子贞不字，十年乃字。",
            "六三：即鹿无虞，惟入于林中。君子几，不如舍。往，吝。",
            "六四：乘马班如，求婚媾。往，吉。无不利。",
            "九五：屯其膏。小贞吉；大贞凶。",
            "上六：乘马班如，泣血涟如。"
        ],
        "fullName": "水雷屯（屯卦）",
        "characteristics": "起始维艰",
        "level": "下下卦",
        "xiangYue": "风刮乱丝不见头，颠三倒四犯忧愁，慢从款来左顺遂，急促反惹不自由。",
        "description": "这个卦是异卦（下震上坎）相叠，震为雷，喻动；坎为雨，喻险。雷雨交加，险象丛生，环境恶劣。\"屯\"原指植物萌生大地。万物始生，充满艰难险阻，然而顺时应运，必欣欣向荣。",
        "alias": "水雷屯",
        "upperTrigram": "坎",
        "lowerTrigram": "震",
        "mutualHexagram": 23,
        "reverseHexagram": 4,
        "oppositeHexagram": 4
    },
    {
        "id": 4,
        "name": "蒙卦",
        "pinyin": "Méng Guà",
        "symbol": "䷃",
        "hexagramText": "《蒙》：亨。匪我求童蒙，童蒙求我；初筮告，再三渎，渎则不告。利贞。",
        "yaoTexts": [
            "初六：发蒙，利用刑人。用说桎梏，以往吝。",
            "九二：包蒙，吉。纳妇，吉。子克家。",
            "六三：勿用取女，见金夫，不有躬。无攸利。",
            "六四：困蒙，吝。",
            "六五：童蒙，吉。",
            "上九：击蒙，不利为寇，利御寇。"
        ],
        "fullName": "山水蒙（蒙卦）",
        "characteristics": "启蒙奋发",
        "level": "中下卦",
        "xiangYue": "卦中爻象犯小耗，君子占之运不高，婚姻合伙有琐碎，做事必然受苦劳。",
        "description": "这个卦是异卦（下坎上艮）相叠，艮是山的形象，喻止；坎是水的形象，喻险。卦形为山下有险，仍不停止前进，是为蒙昧，故称蒙卦。但因把握时机，行动切合时宜，因此，具有启蒙和通达的卦象。",
        "alias": "山水蒙",
        "upperTrigram": "艮",
        "lowerTrigram": "坎",
        "mutualHexagram": 24,
        "reverseHexagram": 3,
        "oppositeHexagram": 3
    },
    {
        "id": 5,
        "name": "需卦",
        "pinyin": "Xū Guà",
        "symbol": "䷄",
        "hexagramText": "《需》：有孚，光亨，贞吉。利涉大川。",
        "yaoTexts": [
            "初九：需于郊，利用恒，无咎。",
            "九二：需于沙，小有言，终吉。",
            "九三：需于泥，致寇至。",
            "六四：需于血，出自穴。",
            "九五：需于酒食，贞吉。",
            "上六：入于穴，有不速之客三人来，敬之，终吉。"
        ],
        "fullName": "水天需（需卦）",
        "characteristics": "守正待机",
        "level": "中上卦",
        "xiangYue": "明珠土埋日久深，无光无亮到如今，忽然大风吹土去，自然显露有重新。",
        "description": "这个卦是异卦（下乾上坎）相叠，下卦是乾，刚健之意；上卦是坎，险陷之意。以刚逢险，宜稳健之妥，不可冒失行动，观时待变，所往一定成功。",
        "alias": "水天需",
        "upperTrigram": "坎",
        "lowerTrigram": "乾",
        "mutualHexagram": 28,
        "reverseHexagram": 6,
        "oppositeHexagram": 35
    },
    {
        "id": 6,
        "name": "讼卦",
        "pinyin": "Sòng Guà",
        "symbol": "䷅",
        "hexagramText": "《讼》：有孚窒惕，中吉；终凶，利见大人，不利涉大川。",
        "yaoTexts": [
            "初六：不永所事，小有言，终吉。",
            "九二：不克讼，归而逋，其邑人三百户。无眚。",
            "六三：食旧德，贞厉，终吉；或从王事，无成。",
            "九四：不克讼，复即命，渝。安贞，吉。",
            "九五：讼，元吉。",
            "上九：或锡之鞶带，终朝三褫之。"
        ],
        "fullName": "天水讼（讼卦）",
        "characteristics": "慎争戒讼",
        "level": "中下卦",
        "xiangYue": "心中有事事难做，恰是二人争路走，雨下俱是要占先，谁肯让谁走一步。",
        "description": "这个卦是异卦（下坎上乾）相叠。同需卦相反，互为\"综卦\"。乾为刚健，坎为险陷。刚与险，健与险，彼此反对，定生争讼。争讼非善事，务必慎重戒惧。",
        "alias": "天水讼",
        "upperTrigram": "乾",
        "lowerTrigram": "坎",
        "mutualHexagram": 28,
        "reverseHexagram": 5,
        "oppositeHexagram": 36
    },
    {
        "id": 7,
        "name": "师卦",
        "pinyin": "Shī Guà",
        "symbol": "䷆",
        "hexagramText": "师：贞，丈人吉，无咎。",
        "yaoTexts": [
            "初六：师出以律，否臧凶。",
            "九二：在师中，吉，无咎。王三锡命。",
            "六三：师或舆尸，凶。",
            "六四：师左次，无咎。",
            "六五：田有禽，利执言，无咎。长子帅师，弟子舆尸，贞凶。",
            "上六：大君有命，开国承家，小人勿用。"
        ],
        "fullName": "地水师（师卦）",
        "characteristics": "行险而顺",
        "level": "中上卦",
        "xiangYue": "将帅领旨去出征，骑着烈马拉硬弓，百步穿杨去得准，箭中金钱喜气生。",
        "description": "这个卦是异卦（下坎上坤）相叠。\"师\"指军队。坎为水、为险；坤为地、为顺，喻寓兵于农。兵凶战危，用兵乃圣人不得已而为之，但它可以顺利无阻碍地解决矛盾，因为顺乎形势，师出有名，故能化凶为吉。",
        "alias": "地水师",
        "upperTrigram": "坤",
        "lowerTrigram": "坎",
        "mutualHexagram": 24,
        "reverseHexagram": 8,
        "oppositeHexagram": 13
    },
    {
        "id": 8,
        "name": "比卦",
        "pinyin": "Bǐ Guà",
        "symbol": "䷇",
        "hexagramText": "比：吉。原筮，元永贞。无咎。不宁方来，后夫凶。",
        "yaoTexts": [
            "初六：有孚比之，无咎。有孚盈缶，终来。有它，吉。",
            "六二：比之自内，贞吉。",
            "六三：比之匪人。",
            "六四：外比之，贞吉。",
            "九五：显比；王用三驱，失前禽，邑人不诫，吉。",
            "上六：比之无首，凶。"
        ],
        "fullName": "水地比（比卦）",
        "characteristics": "诚信团结",
        "level": "上上卦",
        "xiangYue": "顺风行船撒起帆，上天又助一蓬风，不用费力逍遥去，任意而行大亨通。",
        "description": "这个卦是异卦（下坤上坎）相叠，坤为地；坎为水。水附大地，地纳河海，相互依赖，亲密无间。此卦与师卦完全相反，互为综卦。它阐述的是相亲相辅，宽宏无私，精诚团结的道理。",
        "alias": "水地比",
        "upperTrigram": "坎",
        "lowerTrigram": "坤",
        "mutualHexagram": 23,
        "reverseHexagram": 7,
        "oppositeHexagram": 14
    },
    {
        "id": 9,
        "name": "小畜卦",
        "pinyin": "Xiǎo Xù Guà",
        "symbol": "䷈",
        "hexagramText": "小畜：亨。密云不雨，自我西郊。",
        "yaoTexts": [
            "初九：复自道，何其咎？吉。",
            "九二：牵复，吉。",
            "九三：舆说辐，夫妻反目。",
            "六四：有孚，血去惕出，无咎。",
            "九五：有孚挛如，富以其邻。",
            "上九：既雨既处，尚德载；妇贞厉，月几望；君子征凶。"
        ],
        "fullName": "风天小畜（小畜卦）",
        "characteristics": "蓄养待进",
        "level": "下下卦",
        "xiangYue": "苗逢旱天尽焦梢，水想云浓雨不浇，农人仰面长吁气，是从款来莫心高。",
        "description": "这个卦是异卦（下乾上巽）相叠，乾为天；巽为风。喻风调雨顺，谷物滋长，故卦名小畜（蓄）。力量有限，须待发展到一定程度，才可大有作为。",
        "alias": "风天小畜",
        "upperTrigram": "巽",
        "lowerTrigram": "乾",
        "mutualHexagram": 28,
        "reverseHexagram": 10,
        "oppositeHexagram": 26
    },
    {
        "id": 10,
        "name": "履卦",
        "pinyin": "Lǚ Guà",
        "symbol": "䷉",
        "hexagramText": "履：履虎尾，不咥人，亨。",
        "yaoTexts": [
            "初九：素履，往无咎。",
            "九二：履道坦坦，幽人贞吉。",
            "六三：眇能视，跛能履，履虎尾咥人，凶。武人为于大君。",
            "九四：履虎尾，愬愬，终吉。",
            "九五：夬履，贞厉。",
            "上九：视履考祥，其旋元吉。"
        ],
        "fullName": "天泽履（履卦）",
        "characteristics": "脚踏实地",
        "level": "中上卦",
        "xiangYue": "凤凰落在西岐山，长鸣几声出圣贤，天降文王开基业，富贵荣华八百年。",
        "description": "这个卦是异卦（下兑上乾）相叠，乾为天；兑为泽，以天喻君，以泽喻民，原文：\"履（踩）虎尾、不咥（咬）人。\"因此，结果吉利。君上民下，各得其位。兑柔遇乾刚，所履危。履意为实践，卦义是脚踏实地的向前进取的意思。",
        "alias": "天泽履",
        "upperTrigram": "乾",
        "lowerTrigram": "兑",
        "mutualHexagram": 43,
        "reverseHexagram": 9,
        "oppositeHexagram": 15
    },
    {
        "id": 11,
        "name": "泰卦",
        "pinyin": "Tài Guà",
        "symbol": "䷊",
        "hexagramText": "泰：小往大来，吉亨。",
        "yaoTexts": [
            "初九：拔茅茹，以其汇；征吉。",
            "九二：包荒，用冯河，不遐遗。朋亡，得尚于中行。",
            "九三：无平不陂，无往不复。艰贞无咎。勿恤其孚，于食有福。",
            "六四：翩翩，不富，以其邻不戒以孚。",
            "六五：帝乙归妹，以祉元吉。",
            "上六：城复于隍。勿用师，自邑告命。贞吝。"
        ],
        "fullName": "地天泰（泰卦）",
        "characteristics": "应时而变",
        "level": "中中卦",
        "xiangYue": "学文满腹入场闱，三元及第得意回，从今解去愁和闷，喜庆平地一声雷。",
        "description": "这个卦是异卦（下乾上坤）相叠，乾为天，为阳；坤为地，为阴，阴阳交感，上下互通，天地相交，万物纷纭。反之则凶。万事万物，皆对立，转化，盛极必衰，衰而转盛，故应时而变者泰（通）。",
        "alias": "地天泰",
        "upperTrigram": "坤",
        "lowerTrigram": "乾",
        "mutualHexagram": 2,
        "reverseHexagram": 12,
        "oppositeHexagram": 12
    },
    {
        "id": 12,
        "name": "否卦",
        "pinyin": "Pǐ Guà",
        "symbol": "䷋",
        "hexagramText": "《否》：否之匪人，不利，君子贞；大往小来。",
        "yaoTexts": [
            "初六：拔茅茹，以其汇；贞吉，亨。",
            "六二：包承，小人吉；大人否，亨。",
            "六三：包羞。",
            "九四：有命无咎，畴离祉。",
            "九五：休否，大人吉；其亡其亡，系于苞桑。",
            "上九：倾否；先否后喜。"
        ],
        "fullName": "天地否(pǐ)（否卦）",
        "characteristics": "不交不通",
        "level": "中中卦",
        "xiangYue": "虎落陷坑不堪言，进前容易退后难，谋望不遂自己便，疾病口舌事牵连。",
        "description": "这个卦是异卦（下坤上乾）相叠，其结构同泰卦相反，系阳气上升，阴气下降，天地不交，万物不通。它们彼此为\"综卦\"，表明泰极而否，否极泰来，互为因果。",
        "alias": "天地否(pǐ)",
        "upperTrigram": "乾",
        "lowerTrigram": "坤",
        "mutualHexagram": 1,
        "reverseHexagram": 11,
        "oppositeHexagram": 11
    },
    {
        "id": 13,
        "name": "同人卦",
        "pinyin": "Tóng Rén Guà",
        "symbol": "䷌",
        "hexagramText": "同人：同人于野，亨，利涉大川，利君子贞。",
        "yaoTexts": [
            "初九：同人于门，无咎。",
            "六二：同人于宗，吝。",
            "九三：伏戎于莽，升其高陵，三岁不兴。",
            "九四：乘其墉，弗克攻，吉。",
            "九五：同人，先号咷，而后笑，大师克相遇。",
            "上九：同人于郊，无悔。"
        ],
        "fullName": "天火同人（同人卦）",
        "characteristics": "上下和同",
        "level": "中上卦",
        "xiangYue": "心中有事犯猜疑，谋望从前不着实，幸遇明人来指引，诸般忧闷自消之。",
        "description": "这个卦是异卦（下离上乾）相叠，乾为天，为君；离为火，为臣民百姓，上天下火，火性上升，同于天，上下和同，同舟共济，人际关系和谐，天下大同。",
        "alias": "天火同人",
        "upperTrigram": "乾",
        "lowerTrigram": "离",
        "mutualHexagram": 1,
        "reverseHexagram": 14,
        "oppositeHexagram": 7
    },
    {
        "id": 14,
        "name": "大有卦",
        "pinyin": "Dà Yǒu Guà",
        "symbol": "䷍",
        "hexagramText": "大有：元亨。",
        "yaoTexts": [
            "初九：无交害，匪咎；艰则无咎。",
            "九二：大车以载，有攸往，无咎。",
            "九三：公用亨于天子。小人弗克。",
            "九四：匪其彭，无咎。",
            "九五：厥孚交如，威如，吉。",
            "上九：自天祐之，吉无不利。"
        ],
        "fullName": "火天大有（大有卦）",
        "characteristics": "顺天依时",
        "level": "上上卦",
        "xiangYue": "砍树摸雀作事牢，是非口舌自然消，婚姻合伙不费力，若问走失未逃脱。",
        "description": "这个卦是异卦（下乾上离）相叠。上卦为离，为火；下卦为乾，为天。火在天上，普照万物，万民归顺，顺天依时，大有所成。",
        "alias": "火天大有",
        "upperTrigram": "离",
        "lowerTrigram": "乾",
        "mutualHexagram": 1,
        "reverseHexagram": 13,
        "oppositeHexagram": 8
    },
    {
        "id": 15,
        "name": "谦卦",
        "pinyin": "Qiān Guà",
        "symbol": "䷎",
        "hexagramText": "谦：亨。君子有终。",
        "yaoTexts": [
            "初六：谦谦君子。用涉大川，吉。",
            "六二：鸣谦，贞吉。",
            "九三：劳谦，君子有终，吉。",
            "六四：无不利，撝谦。",
            "六五：不富，以其邻利用侵伐，无不利。",
            "上六：鸣谦，利用行师、征邑国。"
        ],
        "fullName": "地山谦（谦卦）",
        "characteristics": "内高外低",
        "level": "中中卦",
        "xiangYue": "天赐贫人一封金，不争不抢两平分，彼此分得金到手，一切谋望皆遂心。",
        "description": "这个卦是异卦（下艮上坤）相叠，艮为山，坤为地。地面有山，地卑（低）而山高，是为内高外低，比喻功高不自居，名高不自誉，位高不自傲。这就是谦。",
        "alias": "地山谦",
        "upperTrigram": "坤",
        "lowerTrigram": "艮",
        "mutualHexagram": 7,
        "reverseHexagram": 16,
        "oppositeHexagram": 39
    },
    {
        "id": 16,
        "name": "豫卦",
        "pinyin": "Yù Guà",
        "symbol": "䷏",
        "hexagramText": "豫：利建侯，行师。",
        "yaoTexts": [
            "初六：鸣豫，凶。",
            "六二：介于石，不终日，贞吉。",
            "六三：盱豫悔；迟有悔。",
            "九四：由豫，大有得，勿疑。朋盍簪。",
            "六五：贞疾，恒不死。",
            "上六：冥豫，成有渝，无咎。"
        ],
        "fullName": "雷地豫（豫卦）",
        "characteristics": "顺时依势",
        "level": "中中卦",
        "xiangYue": "太公插下杏黄旗，收妖为徒归西岐，自此青龙得了位，一旦谋望百事宜。",
        "description": "这个卦是异卦（下坤上震）相叠，坤为地，为顺；震为雷，为动。雷依时出，预示大地回春。因顺而动，和乐之源。此卦与谦卦互为综卦，交互作用。",
        "alias": "雷地豫",
        "upperTrigram": "震",
        "lowerTrigram": "坤",
        "mutualHexagram": 8,
        "reverseHexagram": 15,
        "oppositeHexagram": 40
    },
    {
        "id": 17,
        "name": "随卦",
        "pinyin": "Suí Guà",
        "symbol": "䷐",
        "hexagramText": "随：元亨，利贞，无咎。",
        "yaoTexts": [
            "初九：官有渝，贞吉。出门交有功。",
            "六二：系小子，失丈夫。",
            "六三：系丈夫，失小子；随有求得，利居贞。",
            "九四：随有获，贞凶；有孚在道，以明，何咎。",
            "九五：孚于嘉，吉。",
            "上六：拘系之，乃从，维之；王用亨于西山。"
        ],
        "fullName": "泽雷随（随卦）",
        "characteristics": "随时变通",
        "level": "中中卦",
        "xiangYue": "泥里步踏这几年，推车靠崖在眼前，目下就该再使力，扒上崖去发财源。",
        "description": "这个卦是异卦（下震上兑）相叠，震为雷、为动；兑为悦。动而悦就是\"随\"。随指相互顺从，己有随物，物能随己，彼此沟通。随必依时顺势，有原则和条件，以坚贞为前提。",
        "alias": "泽雷随",
        "upperTrigram": "兑",
        "lowerTrigram": "震",
        "mutualHexagram": 53,
        "reverseHexagram": 18,
        "oppositeHexagram": 18
    },
    {
        "id": 18,
        "name": "蛊卦",
        "pinyin": "Gǔ Guà",
        "symbol": "䷑",
        "hexagramText": "蛊：元亨。利涉大川；先甲三日，后甲三日。",
        "yaoTexts": [
            "初六：干父之蛊，有子考无咎，厉终吉。",
            "九二：干母之蛊，不可贞。",
            "九三：干父之蛊，小有悔，无大咎。",
            "六四：裕父之蛊，往见吝。",
            "六五：干父之蛊，用誉。",
            "上九：不事王侯，高尚其事。"
        ],
        "fullName": "山风蛊（蛊卦）",
        "characteristics": "振疲起衰",
        "level": "中中卦",
        "xiangYue": "卦中爻象如推磨，顺当为福反为祸，心中有益且迟迟，凡事尽从忙处错。",
        "description": "这个卦是异卦（下巽上艮）相叠，与随卦互为综卦。蛊（gu）本意为事，引申为多事、混乱。器皿久不用而生虫称\"蛊\"，喻天下久安而因循、腐败，必须革新创造，治理整顿，挽救危机，重振事业。",
        "alias": "山风蛊",
        "upperTrigram": "艮",
        "lowerTrigram": "巽",
        "mutualHexagram": 54,
        "reverseHexagram": 17,
        "oppositeHexagram": 17
    },
    {
        "id": 19,
        "name": "临卦",
        "pinyin": "Lín Guà",
        "symbol": "䷒",
        "hexagramText": "《临》：元，亨，利，贞。至于八月有凶。",
        "yaoTexts": [
            "初九：咸临，贞吉。",
            "九二：咸临，吉无不利。",
            "六三：甘临，无攸利。既忧之，无咎。",
            "六四：至临，无咎。",
            "六五：知临，大君之宜，吉。",
            "上六：敦临，吉无咎。"
        ],
        "fullName": "地泽临（临卦）",
        "characteristics": "教民保民",
        "level": "中上卦",
        "xiangYue": "君王无道民倒悬，常想拨云见青天，幸逢明主施仁政，重又安居乐自然。",
        "description": "这个卦是异卦（下兑上坤）相叠。坤为地；兑为泽，地高于泽，泽容于地。喻君主亲临天下，治国安邦，上下融洽。",
        "alias": "地泽临",
        "upperTrigram": "坤",
        "lowerTrigram": "兑",
        "mutualHexagram": 24,
        "reverseHexagram": 20,
        "oppositeHexagram": 20
    },
    {
        "id": 20,
        "name": "观卦",
        "pinyin": "Guān Guà",
        "symbol": "䷓",
        "hexagramText": "《观》：盥而不荐。有孚顒若。",
        "yaoTexts": [
            "初六：童观，小人无咎，君子吝。",
            "六二：窥观，利女贞。",
            "六三：观我生，进退。",
            "六四：观国之光，利用宾于王。",
            "九五：观我生，君子无咎。",
            "上九：观其生，君子无咎。"
        ],
        "fullName": "风地观（观卦）",
        "characteristics": "观下瞻上",
        "level": "中上卦",
        "xiangYue": "卦遇蓬花旱逢河，生意买卖利息多，婚姻自有人来助，出门永不受折磨。",
        "description": "这个卦是异卦（下坤上巽）相叠，风行地上，喻德教遍施。观卦与临卦互为综卦，交相使用。在上者以道义观天下；在下者以敬仰瞻上，人心顺服归从。",
        "alias": "风地观",
        "upperTrigram": "巽",
        "lowerTrigram": "坤",
        "mutualHexagram": 23,
        "reverseHexagram": 19,
        "oppositeHexagram": 19
    },
    {
        "id": 21,
        "name": "噬嗑卦",
        "pinyin": "Shì Kè Guà",
        "symbol": "䷔",
        "hexagramText": "《噬嗑》：亨。利用狱。",
        "yaoTexts": [
            "初九：屦校灭趾，无咎。",
            "六二：噬肤灭鼻，无咎。",
            "六三：噬腊肉，遇毒；小吝，无咎。",
            "九四：噬干胏，得金矢，利艰贞，吉。",
            "六五：噬乾肉，得黄金，贞厉，无咎。",
            "上九：何校灭耳，凶。"
        ],
        "fullName": "火雷噬嗑（噬嗑卦）",
        "characteristics": "刚柔相济",
        "level": "上上卦",
        "xiangYue": "运拙如同身受饥，幸得送饭又送食，适口充腹心欢喜，忧愁从此渐消移。",
        "description": "这个卦是异卦（下震上离）相叠。离为阴卦；震为阳卦。阴阳相交，咬碎硬物，喻恩威并施，宽严结合，刚柔相济。噬嗑（shihe）为上下颚咬合，咀嚼。",
        "alias": "火雷噬嗑",
        "upperTrigram": "离",
        "lowerTrigram": "震",
        "mutualHexagram": 39,
        "reverseHexagram": 22,
        "oppositeHexagram": 22
    },
    {
        "id": 22,
        "name": "贲卦",
        "pinyin": "Bì Guà",
        "symbol": "䷕",
        "hexagramText": "《贲》：亨。小利有攸往。",
        "yaoTexts": [
            "初九：贲其趾，舍车而徒。",
            "六二：贲其须。",
            "九三：贲如濡如，永贞吉。",
            "六四：贲如皤如，白马翰如，匪寇婚媾。",
            "六五：贲于丘园，束帛戋戋，吝，终吉。",
            "上九：白贲，无咎。"
        ],
        "fullName": "山火贲（贲卦）",
        "characteristics": "饰外扬质",
        "level": "中上卦",
        "xiangYue": "近来运转瑞气周，窈窕淑女君子求。钟鼓乐之大吉庆，占者逢之喜临头。",
        "description": "这个卦是异卦（下离上艮）相叠。离为火为明；艮为山为止。文明而有节制。贲（bi）卦论述文与质的关系，以质为主，以文调节。贲，文饰、修饰。",
        "alias": "山火贲",
        "upperTrigram": "艮",
        "lowerTrigram": "离",
        "mutualHexagram": 40,
        "reverseHexagram": 21,
        "oppositeHexagram": 21
    },
    {
        "id": 23,
        "name": "剥卦",
        "pinyin": "Bō Guà",
        "symbol": "䷖",
        "hexagramText": "《剥》：不利有攸往。",
        "yaoTexts": [
            "初六：剥床以足，蔑贞凶。",
            "六二：剥床以辨，蔑贞凶。",
            "六三：剥之，无咎。",
            "六四：剥床以肤，凶。",
            "六五：贯鱼，以宫人宠，无不利。",
            "上九：硕果不食，君子得舆，小人剥庐。"
        ],
        "fullName": "山地剥（剥卦）",
        "characteristics": "顺势而止",
        "level": "中下卦",
        "xiangYue": "鹊遇天晚宿林中，不知林内先有鹰，虽然同处心生恶，卦若逢之是非轻。",
        "description": "这个卦是异卦（下坤上艮）相叠。五阴在下，一阳在上，阴盛而阳孤；高山附于地。二者都是剥落象，故为\"剥卦\"。此卦阴盛阳衰，喻小人得势，君子困顿，事业败坏。",
        "alias": "山地剥",
        "upperTrigram": "艮",
        "lowerTrigram": "坤",
        "mutualHexagram": 2,
        "reverseHexagram": 24,
        "oppositeHexagram": 24
    },
    {
        "id": 24,
        "name": "复卦",
        "pinyin": "Fù Guà",
        "symbol": "䷗",
        "hexagramText": "《复》：亨。出入无疾，朋来无咎。反覆其道，七日来复，利有攸往。",
        "yaoTexts": [
            "初九：不远复，无祗悔，元吉。",
            "六二：休复，吉。",
            "六三：频复，厉无咎。",
            "六四：中行独复。",
            "六五：敦复，无悔。",
            "上六：迷复，凶，有灾眚。用行师，终有大败，以其国君，凶；至于十年，不克征。"
        ],
        "fullName": "地雷复（复卦）",
        "characteristics": "寓动于顺",
        "level": "中中卦",
        "xiangYue": "马氏太公不相合，世人占之忧疑多，恩人无义反为怨，是非平地起风波。",
        "description": "这个卦是异卦（下震上坤）相叠。震为雷、为动；坤为地、为顺，动则顺，顺其自然。动在顺中，内阳外阴，循序运动，进退自如，利于前进。",
        "alias": "地雷复",
        "upperTrigram": "坤",
        "lowerTrigram": "震",
        "mutualHexagram": 2,
        "reverseHexagram": 23,
        "oppositeHexagram": 23
    },
    {
        "id": 25,
        "name": "无妄卦",
        "pinyin": "Wú Wàng Guà",
        "symbol": "䷘",
        "hexagramText": "《无妄》：元，亨，利，贞。其匪正有眚，不利有攸往。",
        "yaoTexts": [
            "初九：无妄，往吉。",
            "六二：不耕获，不菑畲，则利用攸往。",
            "六三：无妄之灾，或系之牛，行人之得，邑人之灾。",
            "九四：可贞。无咎。",
            "九五：无妄之疾，勿药有喜。",
            "上九：无妄，行有眚，无攸利。"
        ],
        "fullName": "天雷无妄（无妄卦）",
        "characteristics": "无妄而得",
        "level": "下下卦",
        "xiangYue": "飞鸟失机落笼中，纵然奋飞不能腾，目下只宜守本分，妄想扒高万不能。",
        "description": "这个卦是异卦（下震上乾）相叠。乾为天为刚为健；震为雷为刚为动。动而健，刚阳盛，人心振奋，必有所得，但唯循纯正，不可妄行。无妄必有获，必可致福。",
        "alias": "天雷无妄",
        "upperTrigram": "乾",
        "lowerTrigram": "震",
        "mutualHexagram": 7,
        "reverseHexagram": 26,
        "oppositeHexagram": 26
    },
    {
        "id": 26,
        "name": "大畜卦",
        "pinyin": "Dà Xù Guà",
        "symbol": "䷙",
        "hexagramText": "《大畜》：利贞，不家食吉，利涉大川。",
        "yaoTexts": [
            "初九：有厉利已。",
            "九二：舆说輹。",
            "九三：良马逐，利艰贞。日闲舆卫，利有攸往。",
            "六四：童牛之牿，元吉。",
            "六五：豶豕之牙，吉。",
            "上九：何天之衢，亨。"
        ],
        "fullName": "山天大畜（大畜卦）",
        "characteristics": "止而不止",
        "level": "中上卦",
        "xiangYue": "忧愁常锁两眉头，千头万绪挂心间，从今以后防开阵，任意行而不相干。",
        "description": "这个卦是异卦（下乾上艮）相叠。乾为天，刚健；艮为山，笃实。畜者积聚，大畜意为大积蓄。为此不畏严重的艰难险阻，努力修身养性以丰富德业。",
        "alias": "山天大畜",
        "upperTrigram": "艮",
        "lowerTrigram": "乾",
        "mutualHexagram": 8,
        "reverseHexagram": 25,
        "oppositeHexagram": 25
    },
    {
        "id": 27,
        "name": "颐卦",
        "pinyin": "Yí Guà",
        "symbol": "䷚",
        "hexagramText": "《颐》：贞吉。观颐，自求口实。",
        "yaoTexts": [
            "初九：舍尔灵龟，观我朵颐，凶。",
            "六二：颠颐，拂经，于丘颐，征凶。",
            "六三：拂颐，贞凶，十年勿用，无攸利。",
            "六四：颠颐吉，虎视眈眈，其欲逐逐，无咎。",
            "六五：拂经，居贞吉，不可涉大川。",
            "上九：由颐，厉吉，利涉大川。"
        ],
        "fullName": "山雷颐（颐卦）",
        "characteristics": "纯正以养",
        "level": "上上卦",
        "xiangYue": "太公独钓渭水河，手执丝杆忧愁多，时来又遇文王访，自此永不受折磨。",
        "description": "这个卦是异卦（下震上艮）相叠。震为雷，艮为山。山在上而雷在下，外实内虚。春暖万物养育，依时养贤育民。阳实阴虚，实者养人，虚者为人养。自食其力。",
        "alias": "山雷颐",
        "upperTrigram": "艮",
        "lowerTrigram": "震",
        "mutualHexagram": 2,
        "reverseHexagram": 27,
        "oppositeHexagram": 28
    },
    {
        "id": 28,
        "name": "大过卦",
        "pinyin": "Dà Guò Guà",
        "symbol": "䷛",
        "hexagramText": "《大过》：栋挠，利有攸往，亨。",
        "yaoTexts": [
            "初六：藉用白茅，无咎。",
            "九二：枯杨生稊，老夫得其女妻，无不利。",
            "九三：栋桡，凶。",
            "九四：栋隆，吉；有它吝。",
            "九五：枯杨生华，老妇得其士夫，无咎无誉。",
            "上六：过涉灭顶，凶，无咎。"
        ],
        "fullName": "泽风大过（大过卦）",
        "characteristics": "非常行动",
        "level": "中下卦",
        "xiangYue": "夜晚梦里梦金银，醒来仍不见一文，目下只宜求本分，思想络是空劳神。",
        "description": "这个卦是异卦（下巽上兑）相叠。兑为泽、为悦，巽为木、为顺，泽水淹舟，遂成大错。阴阳爻相反，阳大阴小，行动非常，有过度形象，内刚外柔。",
        "alias": "泽风大过",
        "upperTrigram": "兑",
        "lowerTrigram": "巽",
        "mutualHexagram": 1,
        "reverseHexagram": 28,
        "oppositeHexagram": 27
    },
    {
        "id": 29,
        "name": "坎卦",
        "pinyin": "Kǎn Guà",
        "symbol": "䷜",
        "hexagramText": "《坎坎》：有孚，维心亨，行有尚。",
        "yaoTexts": [
            "初六：习坎，入于坎窞，凶。",
            "九二：坎有险，求小得。",
            "六三：来之坎，坎险且枕，入于坎窞，勿用。",
            "六四：樽酒簋贰，用缶，纳约自牖，终无咎。",
            "九五：坎不盈，祗既平，无咎。",
            "上六：系用徽纆，窴于丛棘，三岁不得，凶。"
        ],
        "fullName": "坎为水（坎卦）",
        "characteristics": "行险用险",
        "level": "下下卦",
        "xiangYue": "一轮明月照水中，只见影儿不见踪，愚夫当财下去取，摸来摸去一场空。",
        "description": "这个卦是同卦（下坎上坎）相叠。坎为水、为险，两坎相重，险上加险，险阻重重。一阳陷二阴。所幸阴虚阳实，诚信可豁然贯通。虽险难重重，却方能显人性光彩。",
        "alias": "坎为水",
        "upperTrigram": "坎",
        "lowerTrigram": "坎",
        "mutualHexagram": 29,
        "reverseHexagram": 29,
        "oppositeHexagram": 30
    },
    {
        "id": 30,
        "name": "离卦",
        "pinyin": "Lí Guà",
        "symbol": "䷝",
        "hexagramText": "《离》：利贞，亨。畜牝牛，吉。",
        "yaoTexts": [
            "初九：履错然，敬之无咎。",
            "六二：黄离，元吉。",
            "九三：日昃之离，不鼓缶而歌，则大耋之嗟，凶。",
            "九四：突如其来如，焚如，死如，弃如。",
            "六五：出涕沱若，戚嗟若，吉。",
            "上九：王用出征，有嘉折首，获匪其丑，无咎。"
        ],
        "fullName": "离为火（离卦）",
        "characteristics": "附和依托",
        "level": "中上卦",
        "xiangYue": "官人来占主高升，庄农人家产业增，生意买卖利息厚，匠艺占之大亨通。",
        "description": "这个卦是同卦（下离上离）相叠。离者丽也，附着之意，一阴附丽，上下二阳，该卦象征火，内空外明。离为火、为明、太阳反复升落，运行不息，柔顺为心。",
        "alias": "离为火",
        "upperTrigram": "离",
        "lowerTrigram": "离",
        "mutualHexagram": 30,
        "reverseHexagram": 30,
        "oppositeHexagram": 29
    },
    {
        "id": 31,
        "name": "咸卦",
        "pinyin": "Xián Guà",
        "symbol": "䷞",
        "hexagramText": "《咸》：亨，利贞，取女吉。",
        "yaoTexts": [
            "初六：咸其拇。",
            "六二：咸其腓，凶，居吉。",
            "九三：咸其股，执其随，往吝。",
            "九四：贞吉悔亡，憧憧往来，朋从尔思。",
            "九五：咸其脢，无悔。",
            "上六：咸其辅，颊，舌。"
        ],
        "fullName": "泽山咸（咸卦）",
        "characteristics": "相互感应",
        "level": "中上卦",
        "xiangYue": "运去黄金失色，时来棒槌发芽，月令极好无差，且喜心宽意大。",
        "description": "这个卦是异卦（下艮上兑）相叠。艮为山；泽为水。兑柔在上，艮刚在下，水向下渗，柔上而刚下，交相感应。感则成。",
        "alias": "泽山咸",
        "upperTrigram": "兑",
        "lowerTrigram": "艮",
        "mutualHexagram": 43,
        "reverseHexagram": 32,
        "oppositeHexagram": 32
    },
    {
        "id": 32,
        "name": "恒卦",
        "pinyin": "Héng Guà",
        "symbol": "䷟",
        "hexagramText": "《恒》：亨，无咎，利贞，利有攸往。",
        "yaoTexts": [
            "初六：浚恒，贞凶，无攸利。",
            "九二：悔亡。",
            "九三：不恒其德，或承之羞，贞吝。",
            "九四：田无禽。",
            "六五：恒其德，贞，妇人吉，夫子凶。",
            "上六：振恒，凶。"
        ],
        "fullName": "雷风恒（恒卦）",
        "characteristics": "恒心有成",
        "level": "中上卦",
        "xiangYue": "渔翁寻鱼运气好，鱼来撞网跑不了，别人使本挣不来，谁想一到就凑合。",
        "description": "这个卦是异卦（下巽上震）相叠。震为男、为雷；巽为女、为风。震刚在上，巽柔在下。刚上柔下，造化有常，相互助长。阴阳相应，常情，故称为恒。",
        "alias": "雷风恒",
        "upperTrigram": "震",
        "lowerTrigram": "巽",
        "mutualHexagram": 44,
        "reverseHexagram": 31,
        "oppositeHexagram": 31
    },
    {
        "id": 33,
        "name": "遯卦",
        "pinyin": "Dùn Guà",
        "symbol": "䷠",
        "hexagramText": "《遯》：亨，小利贞。",
        "yaoTexts": [
            "初六：遯尾，厉，勿用有攸往。",
            "六二：执之用黄牛之革，莫之胜说。",
            "九三：系遯，有疾厉，畜臣妾吉。",
            "九四：好遯君子吉，小人否。",
            "九五：嘉遯，贞吉。",
            "上九：肥遯，无不利。"
        ],
        "fullName": "天山遁（遁卦）",
        "characteristics": "遁世救世",
        "level": "下下卦",
        "xiangYue": "浓云蔽日不光明，劝君且莫出远行，婚姻求财皆不利，提防口舌到门庭。",
        "description": "这个卦是异卦（下艮上乾）相叠。乾为天，艮为山。天下有山，山高天退。阴长阳消，小人得势，君子退隐，明哲保身，伺机救天下。",
        "alias": "天山遁",
        "upperTrigram": "乾",
        "lowerTrigram": "艮",
        "mutualHexagram": 28,
        "reverseHexagram": 34,
        "oppositeHexagram": 34
    },
    {
        "id": 34,
        "name": "大壮卦",
        "pinyin": "Dà Zhuàng Guà",
        "symbol": "䷡",
        "hexagramText": "《大壮》：利贞。",
        "yaoTexts": [
            "初九：壮于趾，征凶，有孚。",
            "九二：贞吉。",
            "九三：小人用壮，君子用罔，贞厉。羝羊触藩，羸其角。",
            "九四：贞吉，悔亡。藩决不羸，壮于大舆之輹。",
            "六五：丧羊于易，无悔。",
            "上六：羝羊触藩，不能退，不能遂，无攸利，艰则吉。"
        ],
        "fullName": "雷天大壮（大壮卦）",
        "characteristics": "壮勿妄动",
        "level": "中上卦",
        "xiangYue": "卦占工师得大木，眼前该着走上路，时来运转多顺当，有事自管放心宽。",
        "description": "这个卦是异卦（下乾上震）相叠。震为雷；乾为天。乾刚震动。天鸣雷，云雷滚，声势宏大，阳气盛壮，万物生长。刚壮有力故曰壮。大而且壮，故名大壮。四阳壮盛，积极而有所作为，上正下正，标正影直。",
        "alias": "雷天大壮",
        "upperTrigram": "震",
        "lowerTrigram": "乾",
        "mutualHexagram": 43,
        "reverseHexagram": 33,
        "oppositeHexagram": 33
    },
    {
        "id": 35,
        "name": "晋卦",
        "pinyin": "Jìn Guà",
        "symbol": "䷢",
        "hexagramText": "《晋》：康侯用锡马蕃庶，昼日三接。",
        "yaoTexts": [
            "初六：晋如，摧如，贞吉。罔孚，裕无咎。",
            "六二：晋如，愁如，贞吉。受兹介福于，其王母。",
            "六三：众允，悔亡。",
            "九四：晋如鼫鼠，贞厉。",
            "六五：悔亡，失得勿恤，往吉无不利。",
            "上九：晋其角，维用伐邑，厉吉无咎，贞吝。"
        ],
        "fullName": "火地晋（晋卦）",
        "characteristics": "求进发展",
        "level": "中上卦",
        "xiangYue": "锄地锄去苗里草，谁想财帛将人找，一锄锄出银子来，这个运气也算好。",
        "description": "这个卦是异卦（下坤上离）相叠。离为日，为光明；坤为地。太阳高悬，普照大地，大地卑顺，万物生长，光明磊落，柔进上行，喻事业蒸蒸日上。",
        "alias": "火地晋",
        "upperTrigram": "离",
        "lowerTrigram": "坤",
        "mutualHexagram": 39,
        "reverseHexagram": 36,
        "oppositeHexagram": 5
    },
    {
        "id": 36,
        "name": "明夷卦",
        "pinyin": "Míng Yí Guà",
        "symbol": "䷣",
        "hexagramText": "《明夷》：利艰贞。",
        "yaoTexts": [
            "初九：明夷于飞，垂其翼。君子于行，三日不食，有攸往， 主人有言。",
            "六二：明夷，夷于左股，用拯马壮，吉。",
            "九三：明夷于南狩，得其大首，不可疾贞。",
            "六四：入于左腹，获明夷之心，于出门庭。",
            "六五：箕子之明夷，利贞。",
            "上六：不明晦，初登于天，后入于地。"
        ],
        "fullName": "地火明夷（明夷卦）",
        "characteristics": "晦而转明",
        "level": "中下卦",
        "xiangYue": "时乖运拙走不着，急忙过河拆了桥，恩人无义反为怨，凡事无功枉受劳。",
        "description": "这个卦是异卦（下离上坤）相叠。离为明，坤为顺；离为日；坤为地。日没入地，光明受损，前途不明，环境困难，宜遵时养晦，坚守正道，外愚内慧，韬光养晦。",
        "alias": "地火明夷",
        "upperTrigram": "坤",
        "lowerTrigram": "离",
        "mutualHexagram": 40,
        "reverseHexagram": 35,
        "oppositeHexagram": 6
    },
    {
        "id": 37,
        "name": "家人卦",
        "pinyin": "Jiā Rén Guà",
        "symbol": "䷤",
        "hexagramText": "《家人》：利女贞。",
        "yaoTexts": [
            "初九：闲有家，悔亡。",
            "六二：无攸遂，在中馈，贞吉。",
            "九三：家人嗃嗃，悔厉吉；妇子嘻嘻，终吝。",
            "六四：富家，大吉。",
            "九五：王假有家，勿恤，吉。",
            "上九：有孚威如，终吉。"
        ],
        "fullName": "风火家人（家人卦）",
        "characteristics": "诚威治业",
        "level": "下下卦",
        "xiangYue": "一朵鲜花镜中开，看着极好取不来，劝君休把镜花恋，卦若逢之主可怪。",
        "description": "这个卦是异卦（下离上巽）相叠。离为火；巽为风。火使热气上升，成为风。一切事物皆应以内在为本，然后伸延到外。发生于内，形成于外。喻先治家而后治天下，家道正，天下安乐。",
        "alias": "风火家人",
        "upperTrigram": "巽",
        "lowerTrigram": "离",
        "mutualHexagram": 64,
        "reverseHexagram": 38,
        "oppositeHexagram": 38
    },
    {
        "id": 38,
        "name": "睽卦",
        "pinyin": "Kuí Guà",
        "symbol": "䷥",
        "hexagramText": "《睽》：小事吉。",
        "yaoTexts": [
            "初九：悔亡，丧马勿逐，自复；见恶人无咎。",
            "九二：遇主于巷，无咎。",
            "六三：见舆曳，其牛掣，其人天且劓，无初有终。",
            "九四：睽孤，遇元夫，交孚，厉无咎。",
            "六五：悔亡，厥宗噬肤，往何咎？",
            "上九：睽孤，见豕负涂，载鬼一车，先张之弧，后说之弧，匪寇婚媾，往遇雨则吉。"
        ],
        "fullName": "火泽睽（睽卦）",
        "characteristics": "异中求同",
        "level": "下下卦",
        "xiangYue": "此卦占来运气歹，如同太公作买卖，贩猪牛快贩羊迟，猪羊齐贩断了宰。",
        "description": "这个卦是异卦（下兑上离）相叠。离为火；兑为泽。上火下泽，相违不相济。克则生，往复无空。万物有所不同，必有所异，相互矛盾。睽即矛盾。",
        "alias": "火泽睽",
        "upperTrigram": "离",
        "lowerTrigram": "兑",
        "mutualHexagram": 63,
        "reverseHexagram": 37,
        "oppositeHexagram": 37
    },
    {
        "id": 39,
        "name": "蹇卦",
        "pinyin": "Jiǎn Guà",
        "symbol": "䷦",
        "hexagramText": "《蹇》：利西南，不利东北；利见大人，贞吉。",
        "yaoTexts": [
            "初六：往蹇，来誉。",
            "六二：王臣蹇蹇，匪躬之故。",
            "九三：往蹇来反。",
            "六四：往蹇来连。",
            "九五：大蹇朋来。",
            "上六：往蹇来硕，吉；利见大人。"
        ],
        "fullName": "水山蹇（蹇卦）",
        "characteristics": "险阻在前",
        "level": "下下卦",
        "xiangYue": "大雨倾地雪满天，路上行人苦又寒，拖泥带水费尽力，事不遂心且耐烦。",
        "description": "这个卦是异卦（下艮上坎）相叠。坎为水；艮为山。山高水深，困难重重，人生险阻，见险而止，明哲保身，可谓智慧。蹇，跋行艰难。",
        "alias": "水山蹇",
        "upperTrigram": "坎",
        "lowerTrigram": "艮",
        "mutualHexagram": 64,
        "reverseHexagram": 40,
        "oppositeHexagram": 15
    },
    {
        "id": 40,
        "name": "解卦",
        "pinyin": "Jiě Guà",
        "symbol": "䷧",
        "hexagramText": "《解》：利西南，无所往，其来复吉。有攸往，夙吉。",
        "yaoTexts": [
            "初六：无咎。",
            "九二：田获三狐，得黄矢，贞吉。",
            "六三：负且乘，致寇至，贞吝。",
            "九四：解而拇，朋至斯孚。",
            "六五：君子维有解，吉；有孚于小人。",
            "上六：公用射隼，于高墉之上，获之，无不利。"
        ],
        "fullName": "雷水解（解卦）",
        "characteristics": "柔道致治",
        "level": "中上卦",
        "xiangYue": "目下月令如过关，千辛万苦受熬煎，时来恰相有人救，任意所为不相干。",
        "description": "这个卦是异卦（下坎上震）相叠。震为雷、为动；坎为水、为险。险在内，动在外。严冬天地闭塞，静极而动。万象更新，冬去春来，一切消除，是为解。",
        "alias": "雷水解",
        "upperTrigram": "震",
        "lowerTrigram": "坎",
        "mutualHexagram": 63,
        "reverseHexagram": 39,
        "oppositeHexagram": 16
    },
    {
        "id": 41,
        "name": "损卦",
        "pinyin": "Sǔn Guà",
        "symbol": "䷨",
        "hexagramText": "《损》：有孚，元吉，无咎，可贞，利有攸往？曷之用，二簋可用享。",
        "yaoTexts": [
            "初九：已事遄往，无咎。酌损之。",
            "九二：利贞，征凶，弗损益之。",
            "六三：三人行，则损一人；一人行，则得其友。",
            "六四：损其疾，使遄有喜，无咎。",
            "六五：或益之，十朋之龟弗克违，元吉。",
            "上九：弗损益之，无咎，贞吉，利有攸往，得臣无家。"
        ],
        "fullName": "山泽损（损卦）",
        "characteristics": "损益制衡",
        "level": "下下卦",
        "xiangYue": "时运不至费心多，比作推车受折磨，山路崎岖吊下耳，左插右按按不着。",
        "description": "这个卦是异卦（下兑上艮）相叠。艮为山；兑为泽。上山下泽，大泽浸蚀山根。损益相间，损中有益，益中有损。二者之间，不可不慎重对待。损下益上，治理国家，过度会损伤国基。应损则损，但必量力、适度。少损而益最佳。",
        "alias": "山泽损",
        "upperTrigram": "艮",
        "lowerTrigram": "兑",
        "mutualHexagram": 24,
        "reverseHexagram": 42,
        "oppositeHexagram": 42
    },
    {
        "id": 42,
        "name": "益卦",
        "pinyin": "Yì Guà",
        "symbol": "䷩",
        "hexagramText": "《益》：利有攸往，利涉大川。",
        "yaoTexts": [
            "初九：利用为大作，元吉，无咎。",
            "六二：或益之，十朋之龟弗克违，永贞吉。王用享于帝，吉。",
            "六三：益之用凶事，无咎。有孚中行，告公用圭。",
            "六四：中行，告公从。利用为依迁国。",
            "九五：有孚惠心，勿问元吉。有孚惠我德。",
            "上九：莫益之，或击之，立心勿恒，凶。"
        ],
        "fullName": "风雷益（益卦）",
        "characteristics": "损上益下",
        "level": "上上卦",
        "xiangYue": "时来运转吉气发，多年枯木又开花，枝叶重生多茂盛，几人见了几人夸。",
        "description": "这个卦是异卦（下震上巽）相叠。巽为风；震为雷。风雷激荡，其势愈强，雷愈响，风雷相助互长，交相助益。此卦与损卦相反。它是损上以益下，后者是损下以益上。二卦阐述的是损益的原则。",
        "alias": "风雷益",
        "upperTrigram": "巽",
        "lowerTrigram": "震",
        "mutualHexagram": 23,
        "reverseHexagram": 41,
        "oppositeHexagram": 41
    },
    {
        "id": 43,
        "name": "夬卦",
        "pinyin": "Guài Guà",
        "symbol": "䷪",
        "hexagramText": "《夬》：扬于王庭，孚号，有厉，告自邑，不利即戎，利有攸往。",
        "yaoTexts": [
            "初九：壮于前趾，往不胜为咎。",
            "九二：惕号，莫夜有戎，勿恤。",
            "九三：壮于頄，有凶。君子夬夬，独行遇雨，若濡有愠，无咎。",
            "九四：臀无肤，其行次且。牵羊悔亡，闻言不信。",
            "九五：苋陆夬夬，中行无咎。",
            "上六：无号，终有凶。"
        ],
        "fullName": "泽天夬 （夬卦）",
        "characteristics": "决而能和",
        "level": "上上卦",
        "xiangYue": "蜘蛛脱网赛天军，粘住游蜂翅翎毛，幸有大风吹破网，脱离灾难又逍遥。",
        "description": "这个卦是异卦（下乾上兑）相叠。乾为天为健；兑为泽为悦。泽气上升，决注成雨，雨施大地，滋润万物。五阳去一阴，去之不难，决（去之意）即可，故名为夬（guài），夬即决。",
        "alias": "泽天夬 ",
        "upperTrigram": "兑",
        "lowerTrigram": "乾",
        "mutualHexagram": 1,
        "reverseHexagram": 44,
        "oppositeHexagram": 44
    },
    {
        "id": 44,
        "name": "姤卦",
        "pinyin": "Gòu Guà",
        "symbol": "䷫",
        "hexagramText": "《姤》：女壮，勿用取女。",
        "yaoTexts": [
            "初六：系于金柅，贞吉，有攸往，见凶，羸豕孚蹢躅。",
            "九二：包有鱼，无咎，不利宾。",
            "九三：臀无肤，其行次且，厉，无大咎。",
            "九四：包无鱼，起凶。",
            "九五：以杞包瓜，含章，有陨自天。",
            "上九：姤其角，吝，无咎。"
        ],
        "fullName": "天风姤（姤卦）",
        "characteristics": "天下有风",
        "level": "上卦",
        "xiangYue": "他乡遇友喜气欢，须知运气福重添，自今交了顺当运，向后管保不相干。",
        "description": "这个卦是异卦（下巽上乾）相叠。乾为天；巽为风。天下有风，吹遍大地，阴阳交合，万物茂盛。姤（gòu）卦与夬卦相反，互为\"综卦\"。姤即遘，阴阳相遇。但五阳一阴，不能长久相处。",
        "alias": "天风姤",
        "upperTrigram": "乾",
        "lowerTrigram": "巽",
        "mutualHexagram": 1,
        "reverseHexagram": 43,
        "oppositeHexagram": 43
    },
    {
        "id": 45,
        "name": "萃卦",
        "pinyin": "Cuì Guà",
        "symbol": "䷬",
        "hexagramText": "《萃》：亨。王假有庙，利见大人，亨，利贞。用大牲吉，利有攸往。",
        "yaoTexts": [
            "初六：有孚不终，乃乱乃萃，若号一握为笑，勿恤，往无咎。",
            "六二：引吉，无咎，孚乃利用禴。",
            "六三：萃如，嗟如，无攸利，往无咎，小吝。",
            "九四：大吉，无咎。",
            "九五：萃有位，无咎。匪孚，元永贞，悔亡。",
            "上六：赍咨涕洟，无咎。"
        ],
        "fullName": "泽地萃（萃卦）",
        "characteristics": "荟萃聚集",
        "level": "中上卦",
        "xiangYue": "游鱼戏水被网惊，跳过龙门身化龙，三尺杨柳垂金线，万朵桃花显你能。",
        "description": "这个卦是异卦相叠（下坤上兑）。坤为地、为顺；兑为泽、为水。泽泛滥淹没大地，人众多相互斗争，危机必四伏，务必顺天任贤，未雨绸缪，柔顺而又和悦，彼此相得益彰，安居乐业。萃，聚集、团结。",
        "alias": "泽地萃",
        "upperTrigram": "兑",
        "lowerTrigram": "坤",
        "mutualHexagram": 57,
        "reverseHexagram": 46,
        "oppositeHexagram": 46
    },
    {
        "id": 46,
        "name": "升卦",
        "pinyin": "Shēng Guà",
        "symbol": "䷭",
        "hexagramText": "《升》：元亨，用见大人，勿恤，南征吉。",
        "yaoTexts": [
            "初六：允升，大吉。",
            "九二：孚乃利用禴，无咎。",
            "九三：升虚邑。",
            "六四：王用亨于岐山，吉无咎。",
            "六五：贞吉，升阶。",
            "上六：冥升，利于不息之贞。"
        ],
        "fullName": "地风升（升卦）",
        "characteristics": "柔顺谦虚",
        "level": "上上卦",
        "xiangYue": "士人来占必得名，生意买卖也兴隆，匠艺逢之交易好，农间庄稼亦收成。",
        "description": "这个卦是异卦相叠（下巽上坤）。坤为地、为顺；巽为木、为逊。大地生长树木，逐步的成长，日渐高大成材，喻事业步步高升，前程远大，故名\"升\"。",
        "alias": "地风升",
        "upperTrigram": "坤",
        "lowerTrigram": "巽",
        "mutualHexagram": 58,
        "reverseHexagram": 45,
        "oppositeHexagram": 45
    },
    {
        "id": 47,
        "name": "困卦",
        "pinyin": "Kùn Guà",
        "symbol": "䷮",
        "hexagramText": "《困》：亨，贞，大人吉，无咎，有言不信。",
        "yaoTexts": [
            "初六：臀困于株木，入于幽谷，三岁不觌。",
            "九二：困于酒食，朱绂方来，利用享祀，征凶，无咎。",
            "六三：困于石，据于蒺藜，入于其宫，不见其妻，凶。",
            "九四：来徐徐，困于金车，吝，有终。",
            "九五：劓刖，困于赤绂，乃徐有说，利用祭祀。",
            "上六：困于葛藟，于臲臬兀，曰动悔。有悔，征吉。"
        ],
        "fullName": "泽水困（困卦）",
        "characteristics": "困境求通",
        "level": "中上卦",
        "xiangYue": "时运不来好伤怀，撮上押去把梯抬，一筒虫翼无到手，转了上去下不来。",
        "description": "这个卦是异卦（下坎上兑）相叠。兑为阴为泽喻悦；坎为阳为水喻险。泽水困，陷入困境，才智难以施展，仍坚守正道，自得其乐，必可成事，摆脱困境。",
        "alias": "泽水困",
        "upperTrigram": "兑",
        "lowerTrigram": "坎",
        "mutualHexagram": 28,
        "reverseHexagram": 48,
        "oppositeHexagram": 48
    },
    {
        "id": 48,
        "name": "井卦",
        "pinyin": "Jǐng Guà",
        "symbol": "䷯",
        "hexagramText": "《井》：改邑不改井，无丧无得，往来井井。汔至，亦未繘井，羸其瓶，凶。",
        "yaoTexts": [
            "初六：井泥不食，旧井无禽。",
            "九二：井谷射鲋，瓮敝漏。",
            "九三：井渫不食，为我心恻，可用汲，王明，并受其福。",
            "六四：井甃，无咎。",
            "九五：井洌，寒泉食。",
            "上六：井收勿幕，有孚元吉。"
        ],
        "fullName": "水风井（井卦）",
        "characteristics": "求贤若渴",
        "level": "上上卦",
        "xiangYue": "枯井破费已多年，一朝流泉出来鲜，资生济渴人称羡，时来运转喜自然。",
        "description": "这个卦是异卦（下巽上坎）相叠。坎为水；巽为木。树木得水而蓬勃生长。人靠水井生活，水井由人挖掘而成。相互为养，井以水养人，经久不竭，人应取此德而勤劳自勉。",
        "alias": "水风井",
        "upperTrigram": "坎",
        "lowerTrigram": "巽",
        "mutualHexagram": 28,
        "reverseHexagram": 47,
        "oppositeHexagram": 47
    },
    {
        "id": 49,
        "name": "革卦",
        "pinyin": "Gé Guà",
        "symbol": "䷰",
        "hexagramText": "《革》：巳日乃孚，元亨利贞，悔亡。",
        "yaoTexts": [
            "初九：巩用黄牛之革。",
            "六二：巳日乃革之，征吉，无咎。",
            "九三：征凶，贞厉，革言三就，有孚。",
            "九四：悔亡，有孚改命，吉。",
            "九五：大人虎变，未占有孚。",
            "上六：君子豹变，小人革面，征凶，居贞吉。"
        ],
        "fullName": "泽火革（革卦）",
        "characteristics": "顺天应人",
        "level": "上上卦",
        "xiangYue": "苗逢旱天渐渐衰，幸得天恩降雨来，忧去喜来能变化，求谋干事遂心怀。",
        "description": "这个卦是异卦（下离上兑）相叠。离为火；兑为泽，泽内有水。水在上而下浇，火在下而上升。火旺水干；水大火熄。二者相生亦相克，必然出现变革。变革是宇宙的基本规律。",
        "alias": "泽火革",
        "upperTrigram": "兑",
        "lowerTrigram": "离",
        "mutualHexagram": 43,
        "reverseHexagram": 50,
        "oppositeHexagram": 50
    },
    {
        "id": 50,
        "name": "鼎卦",
        "pinyin": "Dǐng Guà",
        "symbol": "䷱",
        "hexagramText": "《鼎》：元吉，亨。",
        "yaoTexts": [
            "初六：鼎颠趾，利出否，得妾以其子，无咎。",
            "九二：鼎有实，我仇有疾，不我能即，吉。",
            "九三：鼎耳革，其行塞，雉膏不食，方雨亏悔，终吉。",
            "九四：鼎折足，覆公餗，其形渥，凶。",
            "六五：鼎黄耳金铉，利贞。",
            "上九：鼎玉铉，大吉，无不利。"
        ],
        "fullName": "火风鼎（鼎卦）",
        "characteristics": "稳重图变",
        "level": "中下卦",
        "xiangYue": "莺鹜蛤蜊落沙滩，蛤蜊莺鹜两翅扇，渔人进前双得利，失走行人却自在。",
        "description": "这个卦是异卦（下巽上离）相叠。燃木煮食，化生为熟，除旧布新的意思。鼎为重宝大器，三足稳重之象。煮食，喻食物充足，不再有困难和困扰。在此基础上宜变革，发展事业。",
        "alias": "火风鼎",
        "upperTrigram": "离",
        "lowerTrigram": "巽",
        "mutualHexagram": 44,
        "reverseHexagram": 49,
        "oppositeHexagram": 49
    },
    {
        "id": 51,
        "name": "震卦",
        "pinyin": "Zhèn Guà",
        "symbol": "䷲",
        "hexagramText": "《震》：亨。震来虩虩，笑言哑哑。震惊百里，不丧匕鬯。",
        "yaoTexts": [
            "初九：震来虩虩，后笑言哑哑，吉。",
            "六二：震来厉，亿丧贝，跻于九陵，勿逐，七日得。",
            "六三：震苏苏，震行无眚。",
            "九四：震遂泥。",
            "六五：震往来厉，意无丧，有事。",
            "上六：震索索，视矍矍，征凶。震不于其躬，于其邻，无咎。婚媾有言。"
        ],
        "fullName": "震为雷（震卦）",
        "characteristics": "临危不乱",
        "level": "中上卦",
        "xiangYue": "一口金钟在淤泥，人人拿着当玩石，忽然一日钟悬起，响亮一声天下知。",
        "description": "这个卦是同卦（下震上震）相叠。震为雷，两震相叠，反响巨大，可消除沉闷之气，亨通畅达。平日应居安思危，怀恐惧心理，不敢有所怠慢，遇到突发事变，也能安然自若，谈笑如常。",
        "alias": "震为雷",
        "upperTrigram": "震",
        "lowerTrigram": "震",
        "mutualHexagram": 29,
        "reverseHexagram": 51,
        "oppositeHexagram": 52
    },
    {
        "id": 52,
        "name": "艮卦",
        "pinyin": "Gèn Guà",
        "symbol": "䷳",
        "hexagramText": "《艮》：艮其背，不获其身，行其庭，不见其人，无咎。",
        "yaoTexts": [
            "初六：艮其趾，无咎，利永贞。",
            "六二：艮其腓，不拯其随，其心不快。",
            "九三：艮其限，列其夤，厉熏心。",
            "六四：艮其身，无咎。",
            "六五：艮其辅，言有序，悔亡。",
            "上九：敦艮，吉。"
        ],
        "fullName": "艮为山（艮卦）",
        "characteristics": "动静适时",
        "level": "中下卦",
        "xiangYue": "财帛常打心头走，可惜眼前难到手，不如意时且忍耐，逢着闲事休开口。",
        "description": "这个卦是同卦（下艮上艮）相叠。艮为山，二山相重，喻静止。它和震卦相反。高潮过后，必然出现低潮，进入事物的相对静止阶段。静止如山，宜止则止，宜行则行。行止即动和静，都不可失机，应恰到好处，动静得宜，适可而止。",
        "alias": "艮为山",
        "upperTrigram": "艮",
        "lowerTrigram": "艮",
        "mutualHexagram": 29,
        "reverseHexagram": 52,
        "oppositeHexagram": 51
    },
    {
        "id": 53,
        "name": "渐卦",
        "pinyin": "Jiàn Guà",
        "symbol": "䷴",
        "hexagramText": "《渐》：女归吉，利贞。",
        "yaoTexts": [
            "初六：鸿渐于干，小子厉，有言，无咎。",
            "六二：鸿渐于磐，饮食衎衎，吉。",
            "九三：鸿渐于陆，夫征不复，妇孕不育，凶；利御寇。",
            "六四：鸿渐于木，或得其桷，无咎。",
            "九五：鸿渐于陵，妇三岁不孕，终莫之胜，吉。",
            "上九：鸿渐于陆，其羽可用为仪，吉。"
        ],
        "fullName": "风山渐（渐卦）",
        "characteristics": "渐进蓄德",
        "level": "上上卦",
        "xiangYue": "俊鸟幸得出笼中，脱离灾难显威风，一朝得意福力至，东西南北任意行。",
        "description": "这个卦是异卦（下艮上巽）相叠。艮为山；巽为木。山上有木，逐渐成长，山也随着增高。这是逐渐进步的过程，所以称渐，渐即进，渐渐前进而不急速。",
        "alias": "风山渐",
        "upperTrigram": "巽",
        "lowerTrigram": "艮",
        "mutualHexagram": 63,
        "reverseHexagram": 54,
        "oppositeHexagram": 54
    },
    {
        "id": 54,
        "name": "归妹卦",
        "pinyin": "Guī Mèi Guà",
        "symbol": "䷵",
        "hexagramText": "《归妹》：征凶，无攸利。",
        "yaoTexts": [
            "初九：归妹以娣，跛能履，征吉。",
            "九二：眇能视，利幽人之贞。",
            "六三：归妹以须，反归以娣。",
            "九四：归妹愆期，迟归有时。",
            "六五：帝乙归妹，其君之袂，不如其娣之袂良，月几望，吉。",
            "上六：女承筐无实，士刲羊无血，无攸利。"
        ],
        "fullName": "雷泽归妹（归妹卦）",
        "characteristics": "立家兴业",
        "level": "下下卦",
        "xiangYue": "求鱼须当向水中，树上求之不顺情，受尽爬揭难随意，劳而无功运平平。",
        "description": "这个卦是异卦（下兑上震）相叠。震为动、为长男；兑为悦、为少女。以少女从长男，产生爱慕之情，有婚姻之动，有嫁女之象，故称归妹。男婚女嫁，天地大义，人的开始和终结。上卦与渐卦为综卦，交互为用。",
        "alias": "雷泽归妹",
        "upperTrigram": "震",
        "lowerTrigram": "兑",
        "mutualHexagram": 64,
        "reverseHexagram": 53,
        "oppositeHexagram": 53
    },
    {
        "id": 55,
        "name": "丰卦",
        "pinyin": "Fēng Guà",
        "symbol": "䷶",
        "hexagramText": "《丰》：亨，王假之，勿忧，宜日中。",
        "yaoTexts": [
            "初九：遇其配主，虽旬无咎，往有尚。",
            "六二：丰其蔀，日中见斗，往得疑疾，有孚发若，吉。",
            "九三：丰其沛，日中见沫，折其右肱，无咎。",
            "九四：丰其蔀，日中见斗，遇其夷主，吉。",
            "六五：来章，有庆誉，吉。",
            "上六：丰其屋，蔀其家，窥其户，阒其无人，三岁不觌，凶。"
        ],
        "fullName": "雷火丰（丰卦）",
        "characteristics": "日中则斜",
        "level": "上上卦",
        "xiangYue": "古镜昏暗好几年，一朝磨明似月圆，君子谋事逢此卦，时来运转喜自然。",
        "description": "这个卦是异卦（下离上震）相叠，电闪雷鸣，成就巨大，喻达到顶峰，如日中天。告诫；务必注意事物向相反方面发展。治乱相因，盛衰无常，不可不警惕。",
        "alias": "雷火丰",
        "upperTrigram": "震",
        "lowerTrigram": "离",
        "mutualHexagram": 28,
        "reverseHexagram": 56,
        "oppositeHexagram": 56
    },
    {
        "id": 56,
        "name": "旅卦",
        "pinyin": "Lǚ Guà",
        "symbol": "䷷",
        "hexagramText": "《旅》：小亨，旅贞吉。",
        "yaoTexts": [
            "初六：旅琐琐，斯其所取灾。",
            "六二：旅即次，怀其资，得童仆贞。",
            "九三：旅焚其次，丧其童仆，贞厉。",
            "九四：旅于处，得其资斧，我心不快。",
            "六五：射雉一矢亡，终以誉命。",
            "上九：鸟焚其巢，旅人先笑，后号啕。丧牛于易，凶。"
        ],
        "fullName": "火山旅（旅卦）",
        "characteristics": "依义顺时",
        "level": "下下卦",
        "xiangYue": "飞鸟树上垒窝巢，小人使计举火烧，君占此卦为不吉，一切谋望枉徒劳。",
        "description": "这个卦是异卦（下艮上离）相叠。此卦与丰卦相反，互为\"综卦\"。山中燃火，烧而不止，火势不停地向前蔓延，如同途中行人，急于赶路。因而称旅卦。",
        "alias": "火山旅",
        "upperTrigram": "离",
        "lowerTrigram": "艮",
        "mutualHexagram": 28,
        "reverseHexagram": 55,
        "oppositeHexagram": 55
    },
    {
        "id": 57,
        "name": "巽卦",
        "pinyin": "Xùn Guà",
        "symbol": "䷸",
        "hexagramText": "《巽》：小亨，利有攸往，利见大人。",
        "yaoTexts": [
            "初六：进退，利武人之贞。",
            "九二：巽在床下，用史巫纷若吉，无咎。",
            "九三：频巽，吝。",
            "六四：悔亡，田获三品。",
            "九五：贞吉悔亡，无不利。无初有终，先庚三日，后庚三日，吉。",
            "上九：巽在床下，丧其资斧，贞凶。"
        ],
        "fullName": "巽为风（巽卦）",
        "characteristics": "谦逊受益",
        "level": "中上卦",
        "xiangYue": "一叶孤舟落沙滩，有篙无水进退难，时逢大雨江湖溢，不用费力任往返。",
        "description": "这个卦是同卦（下巽上巽）相叠，巽（xùn）为风，两风相重，长风不绝，无孔不入，巽义为顺。谦逊的态度和行为可无往不利。",
        "alias": "巽为风",
        "upperTrigram": "巽",
        "lowerTrigram": "巽",
        "mutualHexagram": 58,
        "reverseHexagram": 57,
        "oppositeHexagram": 58
    },
    {
        "id": 58,
        "name": "兑卦",
        "pinyin": "Duì Guà",
        "symbol": "䷹",
        "hexagramText": "《兑》：亨，利贞。",
        "yaoTexts": [
            "初九：和兑，吉。",
            "九二：孚兑，吉，悔亡。",
            "六三：来兑，凶。",
            "九四：商兑，未宁，介疾有喜。",
            "九五：孚于剥，有厉。",
            "上六：引兑。"
        ],
        "fullName": "兑为泽（兑卦）",
        "characteristics": "刚内柔外",
        "level": "上上卦",
        "xiangYue": "这个卦象真可取，觉着做事不费力，休要错过这机关，事事觉得随心意。",
        "description": "这个卦是同卦（下泽上泽）相叠。泽为水。两泽相连，两水交流，上下相和，团结一致，朋友相助，欢欣喜悦。兑为悦也。同秉刚健之德，外抱柔和之姿，坚行正道，导民向上。",
        "alias": "兑为泽",
        "upperTrigram": "兑",
        "lowerTrigram": "兑",
        "mutualHexagram": 57,
        "reverseHexagram": 58,
        "oppositeHexagram": 57
    },
    {
        "id": 59,
        "name": "涣卦",
        "pinyin": "Huàn Guà",
        "symbol": "䷺",
        "hexagramText": "《涣》：亨。王假有庙，利涉大川，利贞。",
        "yaoTexts": [
            "初六：用拯马壮，吉。",
            "九二：涣奔其机，悔亡。",
            "六三：涣其躬，无悔。",
            "六四：涣其群，元吉。涣有丘，匪夷所思。",
            "九五：涣汗其大号，涣王居，无咎。",
            "上九：涣其血，去逖出，无咎。"
        ],
        "fullName": "风水涣（涣卦）",
        "characteristics": "拯救涣散",
        "level": "下下卦",
        "xiangYue": "隔河望见一锭金，欲取岸宽水又深，指望资财难到手，昼思夜想枉费心。",
        "description": "这个卦是异卦（下坎上巽）相叠。风在水上行，推波助澜，四方流溢。涣，水流流散之意。象征组织和人心涣散，必用积极的手段和方法克服，战胜弊端，挽救涣散，转危为安。",
        "alias": "风水涣",
        "upperTrigram": "巽",
        "lowerTrigram": "坎",
        "mutualHexagram": 39,
        "reverseHexagram": 60,
        "oppositeHexagram": 60
    },
    {
        "id": 60,
        "name": "节卦",
        "pinyin": "Jié Guà",
        "symbol": "䷻",
        "hexagramText": "《节》：亨。苦节不可贞。",
        "yaoTexts": [
            "初九：不出户庭，无咎。",
            "九二：不出门庭，凶。",
            "六三：不节若，则嗟若，无咎。",
            "六四：安节，亨。",
            "九五：甘节，吉；往有尚。",
            "上六：苦节，贞凶，悔亡。"
        ],
        "fullName": "水泽节（节卦）",
        "characteristics": "万物有节",
        "level": "上上卦",
        "xiangYue": "时来运转喜气生，登台封神姜太公，到此诸神皆退位，纵然有祸不成凶。",
        "description": "这个卦是异卦（下兑上坎）相叠。兑为泽；坎为水。泽有水而流有限，多必溢于泽外。因此要有节度，故称节。节卦与涣卦相反，互为综卦，交相使用。天地有节度才能常新，国家有节度才能安稳，个人有节度才能完美。",
        "alias": "水泽节",
        "upperTrigram": "坎",
        "lowerTrigram": "兑",
        "mutualHexagram": 40,
        "reverseHexagram": 59,
        "oppositeHexagram": 59
    },
    {
        "id": 61,
        "name": "中孚卦",
        "pinyin": "Zhōng Fú Guà",
        "symbol": "䷼",
        "hexagramText": "《中孚》：豚鱼吉，利涉大川，利贞。",
        "yaoTexts": [
            "初九：虞吉，有他不燕。",
            "九二：鸣鹤在阴，其子和之，我有好爵，吾与尔靡之。",
            "六三：得敌，或鼓或罢，或泣或歌。",
            "六四：月几望，马匹亡，无咎。",
            "九五：有孚挛如，无咎。",
            "上九：翰音登于天，贞凶。"
        ],
        "fullName": "风泽中孚（中孚卦）",
        "characteristics": "诚信立身",
        "level": "下下卦",
        "xiangYue": "路上行人色匆匆，急忙无桥过薄冰，小心谨慎过得去，一步错了落水中。",
        "description": "这个卦是异卦（下兑上巽）相叠。孚（fú）本义孵，孵卵出壳的日期非常准确，有信的意义。卦形外实内虚，喻心中诚信，所以称中孚卦。这是立身处世的根本。",
        "alias": "风泽中孚",
        "upperTrigram": "巽",
        "lowerTrigram": "兑",
        "mutualHexagram": 39,
        "reverseHexagram": 61,
        "oppositeHexagram": 62
    },
    {
        "id": 62,
        "name": "小过卦",
        "pinyin": "Xiǎo Guò Guà",
        "symbol": "䷽",
        "hexagramText": "《小过》：亨，利贞，可小事，不可大事。飞鸟遗之音，不宜上宜下，大吉。",
        "yaoTexts": [
            "初六：飞鸟以凶。",
            "六二：过其祖，遇其妣；不及其君，遇其臣；无咎。",
            "九三：弗过防之，从或戕之，凶。",
            "九四：无咎，弗过遇之。往厉必戒，勿用永贞。",
            "六五：密云不雨，自我西郊，公弋取彼在穴。",
            "上六：弗遇过之，飞鸟离之，凶，是谓灾眚。"
        ],
        "fullName": "雷山小过（小过卦）",
        "characteristics": "行动有度",
        "level": "中上卦",
        "xiangYue": "行人路过独木桥，心内惶恐眼里瞧，爽利保你过得去，慢行一定不安牢。",
        "description": "这个卦是异卦（下艮上震）相叠。艮为山；震为雷。过山雷鸣，不可不畏惧。阳为大，阴为小，卦外四阴超过中二阳，故称\"小过\"，小有越过。",
        "alias": "雷山小过",
        "upperTrigram": "震",
        "lowerTrigram": "艮",
        "mutualHexagram": 40,
        "reverseHexagram": 62,
        "oppositeHexagram": 61
    },
    {
        "id": 63,
        "name": "既济卦",
        "pinyin": "Jì Jì Guà",
        "symbol": "䷾",
        "hexagramText": "《既济》：亨，小利贞，初吉终乱。",
        "yaoTexts": [
            "初九：曳其轮，濡其尾，无咎。",
            "六二：妇丧其茀，勿逐，七日得。",
            "九三：高宗伐鬼方，三年克之，小人勿用。",
            "六四：繻有衣袽，终日戒。",
            "九五：东邻杀牛，不如西邻之禴祭，实受其福。",
            "上六：濡其首，厉。"
        ],
        "fullName": "水火既济（既济卦）",
        "characteristics": "盛极将衰",
        "level": "中上卦",
        "xiangYue": "金榜以上题姓名，不负当年苦用功，人逢此卦名吉庆，一切谋望大亨通。",
        "description": "这个卦是异卦（下离上坎）相叠。坎为水；离为火。水火相交，水在火上，水势压倒火势，救火大功告成。既，已经；济，成也。既济就是事情已经成功，但终将发生变故。",
        "alias": "水火既济",
        "upperTrigram": "坎",
        "lowerTrigram": "离",
        "mutualHexagram": 63,
        "reverseHexagram": 64,
        "oppositeHexagram": 64
    },
    {
        "id": 64,
        "name": "未济卦",
        "pinyin": "Wèi Jì Guà",
        "symbol": "䷿",
        "hexagramText": "《未济》：亨，小狐汔济，濡其尾，无攸利。",
        "yaoTexts": [
            "初六：濡其尾，吝。",
            "九二：曳其轮，贞吉。",
            "六三：未济，征凶，利涉大川。",
            "九四：贞吉，悔亡，震用伐鬼方，三年有赏于大国。",
            "六五：贞吉，无悔，君子之光，有孚，吉。",
            "上九：有孚于饮酒，无咎，濡其首，有孚失是。"
        ],
        "fullName": "火水未济（未济卦）",
        "characteristics": "事业未竟",
        "level": "中下卦",
        "xiangYue": "离地着人几丈深，是防偷营劫寨人，后封太岁为凶煞，时加谨慎祸不侵。",
        "description": "这个卦是异卦（下坎上离）相叠。离为火；坎为水。火上水下，火势压倒水势，救火大功未成，故称未济。《周易》以乾坤二卦为始，以既济、未济二卦为终，充分反映了变化发展的思想。",
        "alias": "火水未济",
        "upperTrigram": "离",
        "lowerTrigram": "坎",
        "mutualHexagram": 64,
        "reverseHexagram": 63,
        "oppositeHexagram": 63
    }
];